---
namespace: nephelaiio
name: patroni
version: 0.4.8
readme: README.md
authors:
  - Ted Cook <358176+teddyphreak@users.noreply.github.com>
description: your collection description
license:
  - MIT
tags:
  - postgresql
  - patroni
dependencies:
  "nephelaiio.plugins": "*"
  "nephelaiio.consul": "*"
  "community.postgresql": "*"
  "community.docker": "*"
  "ansible.windows": "*"
repository: http://github.com/nephelaiio/ansible-collection-patroni
documentation: http://github.com/nephelaiio/ansible-collection-patroni
homepage: http://github.com/nephelaiio/ansible-collection-patroni
issues: http://github.com/nephelaiio/ansible-collection-patroni/issues
build_ignore:
  - .git
  - .devbox
  - .venv
  - .ansible
  - .ansible_collections
  - libvirt
