---
- name: Import configuration playbook
  ansible.builtin.import_playbook: nephelaiio.patroni.configure

- name: Manage pgpass file
  hosts: _patroni_cluster_master
  become: true
  vars_files:
    - ../../../playbooks/vars/main.yml
  tasks:
    - name: Safely execute postgresql query command without authentication
      block:
        - name: Attempt postgresql query without authentication
          community.postgresql.postgresql_query:
            login_db: "{{ patroni_molecule_database }}"
            login_port: "{{ _patroni_haproxy_port_psql_master_local }}"
            login_user: "{{ patroni_molecule_username }}"
            login_host: 127.0.0.1
            query: SELECT * FROM pg_catalog.pg_database;
          become: true
          become_user: "{{ _postgresql_user }}"
          register: _postgresql_query_result

      rescue:
        - name: Verify postgresql query without authentication
          ansible.builtin.assert:
            that: _query is search('no password supplied')
          vars:
            _query: "{{ _postgresql_query_result.msg | default('') }}"

    - name: Run psql command with pgpassfile
      community.postgresql.postgresql_query:
        login_db: "{{ patroni_molecule_database }}"
        login_port: "{{ _patroni_haproxy_port_psql_master_local }}"
        login_user: "{{ patroni_molecule_username }}"
        login_host: 127.0.0.1
        query: SELECT * FROM pg_catalog.pg_database;
        connect_params:
          passfile: "{{ _patroni_cluster_pgpass_path }}"
      become: true
      become_user: "{{ _postgresql_user }}"
      register: _postgresql_query_result

    - name: Verify postgresql query with pgpass
      ansible.builtin.assert:
        that: (not _failed | bool) and (_query_result | length > 0)
      vars:
        _query: "{{ _postgresql_query_result | default({}) }}"
        _failed: "{{ _query.failed | default('false') }}"
        _query_result: "{{ _query.query_result | default([]) }}"

- name: Import pgcron playbook
  ansible.builtin.import_playbook: nephelaiio.patroni.pgcron

- name: Verify pg_cron settings
  hosts: _patroni_cluster_master
  become: true
  vars_files:
    - ../../../playbooks/vars/main.yml
  tasks:
    - name: Wait for pg_cron executions
      ansible.builtin.pause:
        seconds: 60

    - name: Query existing pg_cron
      community.postgresql.postgresql_query:
        login_port: "{{ _patroni_haproxy_port_psql_master_local }}"
        query: "SELECT * FROM cron.job;"
      become_user: "{{ _postgresql_user }}"
      register: _patroni_pgcron_results

    - name: Query running pg_cron jobs
      community.postgresql.postgresql_query:
        login_port: "{{ _patroni_haproxy_port_psql_master_local }}"
        query: "SELECT * FROM cron.job_run_details order by start_time;"
      become_user: "{{ _postgresql_user }}"
      register: _patroni_pgcron_running

    - name: Verify pg_cron jobs
      ansible.builtin.assert:
        that:
          - (_created | length) == (_present | length)
          - _running | length > 0
      vars:
        _default:
          active: true
          database: postgres
          state: present
        _pg_cron: "{{ _patroni_cluster_pg_cron_jobs | sort(attribute='job_name') }}"
        _pg_cron_defaults: "{{ [_default] | product(_pg_cron) | map('combine') }}"
        _existing: "{{ _patroni_pgcron_results.query_result | default([]) }}"
        _present: "{{ _pg_cron_defaults | selectattr('state', 'equalto', 'present') }}"
        _existing_names: "{{ _existing | map(attribute='jobname') }}"
        _created: "{{ _present | selectattr('job_name', 'in', _existing_names) }}"
        _running: "{{ _patroni_pgcron_running.query_result | default([]) }}"

- name: Override pg_cron jobs
  hosts: all
  vars_files:
    - ../../../playbooks/vars/main.yml
  tasks:
    - name: Override pg_cron settings
      ansible.builtin.set_fact:
        patroni_cluster_pg_cron_jobs:
          - job_name: molecule
            schedule: "30 seconds"
            command: "SELECT 1"
            active: false
          - job_name: test
            schedule: "10 3 * * 6"
            command: "SELECT 1"
            state: absent
          - job_name: inventory
            schedule: "30 3 * * 6"
            command: "SELECT 1"

- name: Import pgcron playbook
  ansible.builtin.import_playbook: nephelaiio.patroni.pgcron

- name: Verify pg_cron settings
  hosts: _patroni_cluster_master
  become: true
  vars_files:
    - ../../../playbooks/vars/main.yml
  tasks:
    - name: Query existing pg_cron
      community.postgresql.postgresql_query:
        login_port: "{{ _patroni_haproxy_port_psql_master_local }}"
        query: "SELECT * FROM cron.job;"
      become_user: "{{ _postgresql_user }}"
      register: _patroni_pgcron_results

    - name: Verify pg_cron jobs
      ansible.builtin.assert:
        that:
          - (_targets_disabled | length) == (_existing_disabled | length)
          - _absent | selectattr('job_name', 'in', _existing_names) | length == 0
          - (_existing | length) == (_present | length)
      vars:
        _default:
          active: true
          database: postgres
          state: present
        _pg_cron: "{{ _patroni_cluster_pg_cron_jobs | sort(attribute='job_name') }}"
        _pg_cron_defaults: "{{ [_default] | product(_pg_cron) | map('combine') }}"
        _existing: "{{ _patroni_pgcron_results.query_result | default([]) }}"
        _present: "{{ _pg_cron_defaults | selectattr('state', 'equalto', 'present') }}"
        _existing_disabled: "{{ _existing | rejectattr('active') }}"
        _targets_disabled: "{{ _present | rejectattr('active') }}"
        _absent: "{{ _pg_cron_defaults | difference(_present) }}"
        _existing_names: "{{ _existing | map(attribute='jobname') }}"

- name: Import configuration playbook
  ansible.builtin.import_playbook: nephelaiio.patroni.views

- name: Verify materialized view settings
  hosts: _patroni_cluster_master
  become: true
  vars_files:
    - ../../../playbooks/vars/main.yml
  tasks:
    - name: Set default values for existing views
      ansible.builtin.set_fact:
        _patroni_existing_views: []

    - name: Query existing materialized views
      community.postgresql.postgresql_query:
        login_port: "{{ _patroni_haproxy_port_psql_master_local }}"
        query: "SELECT * FROM pg_matviews;"
        login_db: "{{ _db }}"
      vars:
        _db: "{{ item.login_db }}"
      loop_control:
        label: "{{ _db }}"
      loop: "{{ _patroni_views_overwritten }}"
      become_user: "{{ _postgresql_user }}"
      register: _patroni_view_results

    - name: Set existing materialized view fact
      ansible.builtin.set_fact:
        _patroni_existing_views: "{{ _patroni_existing_views + [_view] }}"
      vars:
        _db: "{{ item.item.login_db }}"
        _query: "{{ item.query_result | default([]) }}"
        _matviewname: "{{ _query | map(attribute='matviewname') | flatten | first }}"
        _view:
          login_db: "{{ _db }}"
          name: "{{ _matviewname }}"
      loop_control:
        label: "{{ _db }}"
      loop: "{{ _patroni_view_results.results | default([]) }}"
      when: _query | length > 0

    - name: Verify materialized view creation tasks
      ansible.builtin.assert:
        that:
          - (_patroni_existing_views | length) == (_present | length)
          - _absent | selectattr('name', 'in', _existing) | length == 0
      vars:
        _default:
          state: present
          schema: public
          login_db: postgres
        _views: "{{ _patroni_cluster_materialized_views | sort(attribute='name') }}"
        _view_defaults: "{{ [_default] | product(_views) | map('combine') }}"
        _existing: "{{ _patroni_existing_views | map(attribute='name') }}"
        _present: "{{ _view_defaults | selectattr('state', 'equalto', 'present') }}"
        _absent: "{{ _view_defaults | difference(_present) }}"

- name: Override materialized views
  hosts: all
  vars_files:
    - ../../../playbooks/vars/main.yml
  tasks:
    - name: Override view settings
      ansible.builtin.set_fact:
        patroni_cluster_materialized_views:
          - name: view_postgres
            query: |
              select 1
            state: absent
          - name: view_test
            query: |
              select 1
            login_db: "{{ patroni_molecule_database }}"

- name: Import configuration playbook
  ansible.builtin.import_playbook: nephelaiio.patroni.views

- name: Verify materialized view settings
  hosts: _patroni_cluster_master
  become: true
  vars_files:
    - ../../../playbooks/vars/main.yml
  tasks:
    - name: Set default values for existing views
      ansible.builtin.set_fact:
        _patroni_existing_views: []

    - name: Query existing materialized views
      community.postgresql.postgresql_query:
        login_port: "{{ _patroni_haproxy_port_psql_master_local }}"
        query: "SELECT * FROM pg_matviews;"
        login_db: "{{ _db }}"
      vars:
        _db: "{{ item.login_db }}"
      loop_control:
        label: "{{ _db }}"
      loop: "{{ _patroni_views_overwritten }}"
      become_user: "{{ _postgresql_user }}"
      register: _patroni_view_results

    - name: Set existing materialized view fact
      ansible.builtin.set_fact:
        _patroni_existing_views: "{{ _patroni_existing_views + [_view] }}"
      vars:
        _db: "{{ item.item.login_db }}"
        _query: "{{ item.query_result | default([]) }}"
        _matviewname: "{{ _query | map(attribute='matviewname') | flatten | first }}"
        _view:
          login_db: "{{ _db }}"
          name: "{{ _matviewname }}"
      loop_control:
        label: "{{ _db }}"
      loop: "{{ _patroni_view_results.results | default([]) }}"
      when: _query | length > 0

    - name: Verify materialized view creation tasks
      ansible.builtin.assert:
        that:
          - (_patroni_existing_views | length) == (_present | length)
          - _absent | selectattr('name', 'in', _existing) | length == 0
      vars:
        _default:
          state: present
          schema: public
          login_db: postgres
        _views: "{{ _patroni_cluster_materialized_views | sort(attribute='name') }}"
        _view_defaults: "{{ [_default] | product(_views) | map('combine') }}"
        _existing: "{{ _patroni_existing_views | map(attribute='name') }}"
        _present: "{{ _view_defaults | selectattr('state', 'equalto', 'present') }}"
        _absent: "{{ _view_defaults | difference(_present) }}"
